<a href="https://colab.research.google.com/github/replyeshab/CineAI-AI-Based-Hybrid-Recommendation-System/blob/main/hybrid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hybrid Recommendation

In [247]:
import numpy as np
import pandas as pd
import pickle

from sklearn.preprocessing import MinMaxScaler

In [248]:
import joblib

ARTIFACT_PATH = "/content/drive/MyDrive/CineAI/Artifact"

movie_data = joblib.load(ARTIFACT_PATH+"/movie_data.pkl")

popular_movies = joblib.load(ARTIFACT_PATH+"/popular_movies.pkl")

svd_model = joblib.load(ARTIFACT_PATH+"/svd_model.pkl")

knn_model = joblib.load(ARTIFACT_PATH+"/knn_content_model.pkl")

tfidf_matrix = joblib.load(ARTIFACT_PATH+"/tfidf_matrix.pkl")

tfidf_vectorizer = joblib.load(ARTIFACT_PATH+"/tfidf_vectorizer.pkl")

title_lookup = joblib.load(ARTIFACT_PATH+"/title_lookup.pkl")

title_to_index = joblib.load(ARTIFACT_PATH+"/title_to_index.pkl")

user_encoder = joblib.load(ARTIFACT_PATH+"/user_encoder.pkl")

movie_encoder = joblib.load(ARTIFACT_PATH+"/movie_encoder.pkl")

user_features = joblib.load(ARTIFACT_PATH + "/user_features.pkl")
movie_features = joblib.load(ARTIFACT_PATH + "/movie_features.pkl")

In [249]:
ratings = pd.read_csv(
    "/content/drive/MyDrive/CineAI/ml-32m/ml-32m/ratings.csv"
)

In [250]:
movie_stats = pd.read_pickle("/content/drive/MyDrive/CineAI/Artifact/movie_stats.pkl")

# Popularity Recommendation

In [251]:
def calculate_imdb_score(df, quantile=0.90):
    """
    Calculates IMDb Weighted Rating.

    Parameters
    ----------
    df : DataFrame
    quantile : float
        Minimum vote percentile.

    Returns
    -------
    DataFrame
    """

    df = df.copy()

    C = df["average_rating"].mean()

    m = df["rating_count"].quantile(quantile)

    df["weighted_rating"] = (
        (
            df["rating_count"] /
            (df["rating_count"] + m)
        ) * df["average_rating"]
    ) + (
        (
            m /
            (df["rating_count"] + m)
        ) * C
    )

    return df

In [252]:
popular_movies = calculate_imdb_score(movie_stats)

In [253]:
popular_movies = (
    popular_movies
    .sort_values(
        by="weighted_rating",
        ascending=False
    )
    .reset_index(drop=True)
)

In [254]:
def recommend_popular(top_n=500):

    columns = [
        "movieId",
        "clean_title",
        "genres",
        "average_rating",
        "rating_count",
        "weighted_rating"
    ]

    return popular_movies[columns].head(top_n)

In [255]:
popular = recommend_popular(20)
popular.head()

,movieId,clean_title,genres,average_rating,rating_count,weighted_rating
0,318,"Shawshank Redemption, The",Crime|Drama,4.404614,102929,4.401238
1,159817,Planet Earth,Documentary,4.444369,2948,4.332311
2,858,"Godfather, The",Crime|Drama,4.317030,66440,4.312134
3,170705,Band of Brothers,Action|Drama|War,4.426539,2811,4.310914
4,202439,Parasite,Comedy|Drama,4.312254,11670,4.284956

# Cold Start

In [256]:
def recommend_cold_start(popular_df, top_n=20):
    """
    Recommend movies for brand-new users.

    Uses popularity only because the user has no history.
    """

    cold_start = (
        popular_df
        .sort_values(
            by=[
                "weighted_rating",
                "rating_count",
                "average_rating"
            ],
            ascending=False
        )
        .head(top_n)
    )

    return cold_start

In [257]:
USER_ID = 1
def is_new_user(user_id, ratings):

    if user_id is None:
        return True

    if user_id not in ratings["userId"].values:
        return True

    return False

def is_sparse_user(
    user_id,
    ratings,
    threshold=10
):

    if is_new_user(user_id, ratings):
        return False

    n = len(
        ratings[
            ratings["userId"] == user_id
        ]
    )

    return n < threshold

In [258]:
USER_ID =1
if is_new_user(USER_ID, ratings):

    print("Cold Start User")

    final_recommendations = recommend_cold_start(
        popular_movies,
        top_n=500
    )

    display(final_recommendations)

    raise SystemExit()

# Collabaorative Recommendation

In [259]:
def rank_candidates(
    candidate_indices,
    scores,
    top_n=500
):

    top_indices = candidate_indices[:top_n]

    movie_ids = movie_encoder.inverse_transform(
        top_indices
    )

    recommendations = (
        movie_data[
            movie_data.movieId.isin(
                movie_ids
            )
        ]
        .copy()
    )

    score_map = {
        movie_encoder.inverse_transform([idx])[0]:
        scores[idx]
        for idx in top_indices
    }

    recommendations["svd_score"] = (
        recommendations.movieId
        .map(score_map)
    )

    return recommendations.sort_values(
        "svd_score",
        ascending=False
    )

In [260]:
def filter_seen_movies(
    user_id,
    candidate_indices,
    scores
):

    watched = ratings.loc[
        ratings.userId == user_id,
        "movieId"
    ]

    watched = watched[
        watched.isin(
            movie_encoder.classes_
        )
    ]

    watched_indices = set(
        movie_encoder.transform(
            watched
        )
    )

    filtered = [
        idx
        for idx in candidate_indices
        if idx not in watched_indices
    ]

    return filtered

In [261]:
def generate_candidates(
    user_id,
    candidate_size=500
):

    if user_id not in user_encoder.classes_:
        raise ValueError("Unknown User ID")

    user_index = user_encoder.transform(
        [user_id]
    )[0]

    user_vector = user_features[user_index]

    scores = movie_features @ user_vector

    top_candidates = np.argsort(
        scores
    )[::-1][:candidate_size]

    return top_candidates, scores

In [262]:
def recommend_for_user_collaborative(
    user_id,
    top_n=500
):

    candidates, scores = generate_candidates(
        user_id
    )

    filtered_candidates = filter_seen_movies(
        user_id,
        candidates,
        scores
    )

    recommendations = rank_candidates(
        filtered_candidates,
        scores,
        top_n
    )

    recommendations = (
        recommendations
        .sort_values("svd_score", ascending=False)
        .reset_index(drop=True)
    )

    recommendations.index.name = "Rank"

    return recommendations

In [263]:
collab = recommend_for_user_collaborative(user_id=1, top_n=20)
collab.head()

,movieId,title,genres,year,clean_title,genres_list,imdbId,tmdbId,tag,combined_features,svd_score
Rank,,,,,,,,,,,
0,858,"Godfather, The (1972)",Crime|Drama,1972.0,"Godfather, The","[Crime, Drama]",68646,238.0,al pacino atmospheric great acting masterpiece...,"Godfather, The Crime Drama Al Pacino atmospher...",2.863783
1,1222,Full Metal Jacket (1987),Drama|War,1987.0,Full Metal Jacket,"[Drama, War]",93058,600.0,vietnam war tumey s dvds imdb top 250 stanley ...,Full Metal Jacket Drama War Vietnam War Tumey'...,2.771993
2,924,2001: A Space Odyssey (1968),Adventure|Drama|Sci-Fi,1968.0,2001: A Space Odyssey,"[Adventure, Drama, Sci-Fi]",62622,62.0,atmospheric space stanley kubrick ambiguous at...,2001: A Space Odyssey Adventure Drama Sci-Fi a...,2.545833
3,750,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War,1964.0,Dr. Strangelove or: How I Learned to Stop Worr...,"[Comedy, War]",57012,935.0,black and white stanley kubrick classic dark c...,Dr. Strangelove or: How I Learned to Stop Worr...,2.479119
4,2858,American Beauty (1999),Drama|Romance,1999.0,American Beauty,"[Drama, Romance]",169547,14.0,bittersweet great acting kevin spacey loneline...,American Beauty Drama Romance bittersweet grea...,2.291048

# Content Recommedation

In [264]:
from sklearn.metrics.pairwise import linear_kernel
def recommend_content(title, top_n=500):

    matches = movie_data[
        movie_data["clean_title"]
        .str.lower() == title.lower()
    ]

    if matches.empty:
        print("Movie not found.")
        return None

    idx = matches.index[0]

    cosine_scores = linear_kernel(
        tfidf_matrix[idx:idx + 1],
        tfidf_matrix
    ).flatten()

    similar_indices = np.argsort(cosine_scores)[::-1]

    similar_indices = similar_indices[1:top_n + 1]

    recommendations = movie_data.iloc[
        similar_indices
    ][["movieId", "clean_title", "genres", "year"]].copy()

    recommendations["similarity_score"] = (
        cosine_scores[similar_indices]
    )

    return recommendations

In [265]:
content = recommend_content("Toy Story", 20)
content.head()

,movieId,clean_title,genres,year,similarity_score
3021,3114,Toy Story 2,Adventure|Animation|Children|Comedy|Fantasy,1999.0,0.892434
2264,2355,"Bug's Life, A",Adventure|Animation|Children|Comedy,1998.0,0.806176
14815,78499,Toy Story 3,Adventure|Animation|Children|Comedy|Fantasy|IMAX,2010.0,0.711669
39850,157296,Finding Dory,Adventure|Animation|Comedy,2016.0,0.701200
4781,4886,"Monsters, Inc.",Adventure|Animation|Children|Comedy|Fantasy,2001.0,0.700583

In [266]:
print(collab.columns)
print(content.columns)
print(popular.columns)

Index(['movieId', 'title', 'genres', 'year', 'clean_title', 'genres_list',
       'imdbId', 'tmdbId', 'tag', 'combined_features', 'svd_score'],
      dtype='object')
Index(['movieId', 'clean_title', 'genres', 'year', 'similarity_score'], dtype='object')
Index(['movieId', 'clean_title', 'genres', 'average_rating', 'rating_count',
       'weighted_rating'],
      dtype='object')

In [267]:
print(collab.head())
print(content.head())
print(popular.head())

      movieId                                              title  \
Rank
0         858                              Godfather, The (1972)
1        1222                           Full Metal Jacket (1987)
2         924                       2001: A Space Odyssey (1968)
3         750  Dr. Strangelove or: How I Learned to Stop Worr...
4        2858                             American Beauty (1999)

                      genres    year  \
Rank
0                Crime|Drama  1972.0
1                  Drama|War  1987.0
2     Adventure|Drama|Sci-Fi  1968.0
3                 Comedy|War  1964.0
4              Drama|Romance  1999.0

                                            clean_title  \
Rank
0                                        Godfather, The
1                                     Full Metal Jacket
2                                 2001: A Space Odyssey
3     Dr. Strangelove or: How I Learned to Stop Worr...
4                                       American Beauty

                     genres_list  imdbId  tmdbId  \
Rank
0                 [Crime, Drama]   68646   238.0
1                   [Drama, War]   93058   600.0
2     [Adventure, Drama, Sci-Fi]   62622    62.0
3                  [Comedy, War]   57012   935.0
4               [Drama, Romance]  169547    14.0

                                                    tag  \
Rank
0     al pacino atmospheric great acting masterpiece...
1     vietnam war tumey s dvds imdb top 250 stanley ...
2     atmospheric space stanley kubrick ambiguous at...
3     black and white stanley kubrick classic dark c...
4     bittersweet great acting kevin spacey loneline...

                                      combined_features  svd_score
Rank
0     Godfather, The Crime Drama Al Pacino atmospher...   2.863783
1     Full Metal Jacket Drama War Vietnam War Tumey'...   2.771993
2     2001: A Space Odyssey Adventure Drama Sci-Fi a...   2.545833
3     Dr. Strangelove or: How I Learned to Stop Worr...   2.479119
4     American Beauty Drama Romance bittersweet grea...   2.291048
       movieId     clean_title  \
3021      3114     Toy Story 2
2264      2355   Bug's Life, A
14815    78499     Toy Story 3
39850   157296    Finding Dory
4781      4886  Monsters, Inc.

                                                 genres    year  \
3021        Adventure|Animation|Children|Comedy|Fantasy  1999.0
2264                Adventure|Animation|Children|Comedy  1998.0
14815  Adventure|Animation|Children|Comedy|Fantasy|IMAX  2010.0
39850                        Adventure|Animation|Comedy  2016.0
4781        Adventure|Animation|Children|Comedy|Fantasy  2001.0

       similarity_score
3021           0.892434
2264           0.806176
14815          0.711669
39850          0.701200
4781           0.700583
   movieId                clean_title            genres  average_rating  \
0      318  Shawshank Redemption, The       Crime|Drama        4.404614
1   159817               Planet Earth       Documentary        4.444369
2      858             Godfather, The       Crime|Drama        4.317030
3   170705           Band of Brothers  Action|Drama|War        4.426539
4   202439                   Parasite      Comedy|Drama        4.312254

   rating_count  weighted_rating
0        102929         4.401238
1          2948         4.332311
2         66440         4.312134
3          2811         4.310914
4         11670         4.284956

In [268]:
collab = (
    collab[
        [
            "movieId",
            "svd_score"
        ]
    ]
    .rename(
        columns={
            "svd_score":"collab_score"
        }
    )
)

In [269]:
content = (
    content[
        [
            "movieId",
            "similarity_score"
        ]
    ]
    .rename(
        columns={
            "similarity_score":"content_score"
        }
    )
)

In [270]:
popular = (
    popular[
        [
            "movieId",
            "average_rating",
            "rating_count",
            "weighted_rating"
        ]
    ]
    .rename(
        columns={
            "weighted_rating":"popularity_score"
        }
    )
)

# Hybrid

In [271]:
hybrid = (
    collab
    .merge(
        content,
        on="movieId",
        how="outer"
    )
    .merge(
        popular,
        on="movieId",
        how="outer"
    )
)

In [272]:
scaler = MinMaxScaler()

In [273]:
score_columns = [
    "collab_score",
    "content_score",
    "popularity_score"
]

for col in score_columns:

    hybrid[col] = scaler.fit_transform(
        hybrid[[col]].fillna(0)
    )

# Genre Recommedation

In [274]:
def build_genre_profile(
    user_id,
    ratings,
    movie_data
):
    """
    Build a weighted genre preference profile
    for one user.

    Higher rated movies contribute more
    than lower rated movies.
    """

    user_ratings = ratings[
        ratings["userId"] == user_id
    ]

    profile = {}

    user_movies = user_ratings.merge(
        movie_data[
            [
                "movieId",
                "genres"
            ]
        ],
        on="movieId",
        how="left"
    )

    for _, row in user_movies.iterrows():

        if pd.isna(row["genres"]):
            continue

        genres = row["genres"].split("|")

        rating = row["rating"]

        for genre in genres:

            if genre == "(no genres listed)":
                continue

            profile[genre] = (
                profile.get(genre, 0)
                + rating
            )

    if len(profile) == 0:
        return {}

    maximum = max(profile.values())

    for genre in profile:

        profile[genre] /= maximum

    return profile

In [275]:
def calculate_genre_score(hybrid_df, genre_profile):

    genre_scores = []

    for _, row in hybrid_df.iterrows():

        if pd.isna(row["genres"]):
            genre_scores.append(0)
            continue

        movie_genres = row["genres"].split("|")

        score = 0

        count = 0

        for genre in movie_genres:

            if genre == "(no genres listed)":
                continue

            score += genre_profile.get(genre, 0)

            count += 1

        if count == 0:
            genre_scores.append(0)

        else:
            genre_scores.append(score / count)

    hybrid_df["genre_score"] = genre_scores

    return hybrid_df

In [276]:
def get_dynamic_weights(
    user_id,
    ratings
):

    if is_new_user(
        user_id,
        ratings
    ):

        return {
            "collab_score":0,
            "content_score":0,
            "popularity_score":0.45,
            "genre_score":0,
            "rating_score":0.25,
            "rating_count_score":0.20,
            "recency_score":0.10
        }

    if is_sparse_user(
        user_id,
        ratings
    ):

        return {
            "collab_score":0.10,
            "content_score":0.40,
            "popularity_score":0.15,
            "genre_score":0.25,
            "rating_score":0.05,
            "rating_count_score":0.03,
            "recency_score":0.02
        }

    return {
        "collab_score":0.20,
        "content_score":0.30,
        "popularity_score":0.15,
        "genre_score":0.20,
        "rating_score":0.05,
        "rating_count_score":0.05,
        "recency_score":0.05
    }

In [277]:
hybrid["rating_score"] = scaler.fit_transform(
    hybrid[
        ["average_rating"]
    ].fillna(0)
)

In [278]:
hybrid["rating_count_score"] = scaler.fit_transform(
    hybrid[
        ["rating_count"]
    ].fillna(0)
)

In [279]:
hybrid = hybrid.merge(
    movie_data[
        ["movieId", "year","genres"]
    ],
    on="movieId",
    how="left"
)

In [280]:
watched_movies = ratings.loc[
    ratings["userId"] == USER_ID,
    "movieId"
]

hybrid = hybrid[
    ~hybrid["movieId"].isin(
        watched_movies
    )
]

In [281]:
genre_profile = build_genre_profile(
    USER_ID,
    ratings,
    movie_data
)

hybrid = calculate_genre_score(
    hybrid,
    genre_profile
)

In [282]:
hybrid["genre_score"] = scaler.fit_transform(
    hybrid[
        ["genre_score"]
    ].fillna(0)
)

In [283]:
CURRENT_YEAR = 2026

hybrid["movie_age"] = (
    CURRENT_YEAR - hybrid["year"]
)

In [284]:
new_movie_mask = (
    hybrid["rating_count"].fillna(0) == 0
)

hybrid.loc[
    new_movie_mask,
    "collab_score"
] = np.nan

hybrid.loc[
    new_movie_mask,
    "popularity_score"
] = np.nan

In [285]:
hybrid["recency_score"] = (
    1 / (1 + hybrid["movie_age"])
)

hybrid["recency_score"] = scaler.fit_transform(
    hybrid[["recency_score"]]
)

In [286]:
hybrid.loc[
    new_movie_mask,
    "movie_age"
] *= 1.20

In [287]:
score_columns = [
    "collab_score",
    "content_score",
    "popularity_score",
    "genre_score",
    "rating_score",
    "rating_count_score",
    "movie_age"
]

In [288]:
def rank_movies(
    df,
    user_id,
    ratings
):

    weights = get_dynamic_weights(
        user_id,
        ratings
    )

    final_scores = []

    for _, row in df.iterrows():

        score = 0
        total_weight = 0

        for feature, weight in weights.items():

            value = row[feature]

            if pd.notna(value):

                score += value * weight

                total_weight += weight

        if total_weight > 0:

            score /= total_weight

        final_scores.append(score)

    df["final_score"] = final_scores

    return df

In [289]:
hybrid = rank_movies(
    hybrid,
    USER_ID,
    ratings
)

In [290]:
def validate_recommendations(
    recommendations,
    watched_movies
):

    assert (
        recommendations["movieId"]
        .duplicated()
        .sum() == 0
    ), "Duplicate recommendations"

    assert (
        len(
            set(
                recommendations["movieId"]
            ).intersection(
                watched_movies
            )
        ) == 0
    ), "Already watched movie recommended"

    assert (
        recommendations["final_score"]
        .isna()
        .sum() == 0
    ), "NaN score detected"

    print("All validation checks passed.")

In [291]:
def get_final_recommendations(df, top_n=500):
    df = df.sort_values(
        "final_score",
        ascending=False
    )

    return df.head(top_n)

final_recommendations = get_final_recommendations(hybrid)
final_recommendations

,movieId,collab_score,content_score,average_rating,rating_count,popularity_score,rating_score,rating_count_score,year,genres,genre_score,movie_age,recency_score,final_score
6,858,1.000000,0.000000,4.317030,66440.0,0.979755,0.970811,0.645493,1972.0,Crime|Drama,0.585635,54.0,0.040280,0.546919
10,1193,0.546209,0.000000,4.204229,44592.0,0.953726,0.945444,0.433231,1975.0,Drama,1.000000,51.0,0.049704,0.523720
31,3114,NaN,1.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,32.4,0.197802,0.520273
28,2355,NaN,0.903345,NaN,NaN,NaN,0.000000,0.000000,1998.0,Adventure|Animation|Children|Comedy,0.162983,33.6,0.186737,0.481442
49,157296,NaN,0.785717,NaN,NaN,NaN,0.000000,0.000000,2016.0,Adventure|Animation|Comedy,0.210866,12.0,0.693706,0.480882
38,50872,NaN,0.717347,NaN,NaN,NaN,0.000000,0.000000,2007.0,Animation|Children|Drama,0.339779,22.8,0.326154,0.460719
5,750,0.865680,0.000000,4.202680,32830.0,0.952839,0.945096,0.318958,1964.0,Comedy|War,0.335635,62.0,0.019536,0.447368
46,103141,NaN,0.740759,NaN,NaN,NaN,0.000000,0.000000,2013.0,Adventure|Animation|Comedy,0.210866,15.6,0.518681,0.446669
41,78499,NaN,0.797447,NaN,NaN,NaN,0.000000,0.000000,2010.0,Adventure|Animation|Children|Comedy|Fantasy|IMAX,0.117864,19.2,0.405430,0.435505
34,6377,NaN,0.780009,NaN,NaN,NaN,0.000000,0.000000,2003.0,Adventure|Animation|Children|Comedy,0.162983,27.6,0.251282,0.429482
35,8961,NaN,0.767647,NaN,NaN,NaN,0.000000,0.000000,2004.0,Action|Adventure|Animation|Children|Comedy,0.173481,26.4,0.267559,0.428259
32,4886,NaN,0.785026,NaN,NaN,NaN,0.000000,0.000000,2001.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,30.0,0.222485,0.422953
39,68954,NaN,0.654754,NaN,NaN,NaN,0.000000,0.000000,2009.0,Adventure|Animation|Children|Drama,0.295580,20.4,0.376068,0.422070
54,201588,NaN,0.632819,NaN,NaN,NaN,0.000000,0.000000,2019.0,Adventure|Animation|Children|Comedy,0.162983,8.4,1.000000,0.419142
37,45517,NaN,0.737091,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.413788
26,2019,0.544298,0.000000,4.249622,16531.0,0.961357,0.955652,0.160606,1954.0,Action|Adventure|Drama,0.459484,72.0,0.000000,0.400773
55,202439,0.000000,0.000000,4.312254,11670.0,0.973580,0.969737,0.113379,2019.0,Comedy|Drama,0.734807,7.0,1.000000,0.397154
40,72356,NaN,0.706746,NaN,NaN,NaN,0.000000,0.000000,2009.0,Animation|Children|Comedy|Fantasy,0.136050,20.4,0.376068,0.396980
45,95858,NaN,0.699901,NaN,NaN,NaN,0.000000,0.000000,2000.0,Animation|Children|Comedy,0.162983,31.2,0.209687,0.389310
42,87876,NaN,0.650932,NaN,NaN,NaN,0.000000,0.000000,2011.0,Adventure|Animation|Children|Comedy|IMAX,0.130387,18.0,0.438462,0.374277
3,318,0.000000,0.000000,4.404614,102929.0,1.000000,0.990506,1.000000,1994.0,Crime|Drama,0.585635,32.0,0.149184,0.374112
47,109420,NaN,0.649240,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.373241
53,175831,NaN,0.670658,NaN,NaN,NaN,0.000000,0.000000,2017.0,Animation,0.000000,10.8,0.775385,0.369179
44,95856,NaN,0.770193,NaN,NaN,NaN,0.000000,0.000000,1989.0,Animation|Children,0.009669,44.4,0.113360,0.367169
2,296,0.000000,0.000000,4.196969,98409.0,0.952905,0.943811,0.956086,1994.0,Comedy|Crime|Drama|Thriller,0.448895,32.0,0.149184,0.335169
48,126405,NaN,0.679593,NaN,NaN,NaN,0.000000,0.000000,1984.0,Animation,0.000000,50.4,0.085868,0.320263
30,2959,0.000000,0.000000,4.228780,77332.0,0.959924,0.950965,0.751314,1999.0,Action|Crime|Drama|Thriller,0.385359,27.0,0.197802,0.316064
43,95375,NaN,0.633491,NaN,NaN,NaN,0.000000,0.000000,2003.0,Animation|Children,0.009669,27.6,0.251282,0.314685
20,1293,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1982.0,Drama,1.000000,52.8,0.076581,0.313583
36,44555,0.000000,0.000000,4.198770,12273.0,0.948606,0.944216,0.119238,2006.0,Drama|Romance|Thriller,0.492634,20.0,0.304762,0.309228
12,1207,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1962.0,Drama,1.000000,76.8,0.015148,0.308858
51,170705,0.000000,0.000000,4.426539,2811.0,0.979478,0.995437,0.027310,2001.0,Action|Drama|War,0.472376,25.0,0.222485,0.303658
0,50,0.000000,0.000000,4.265070,67750.0,0.968014,0.959126,0.658221,1995.0,Crime|Mystery|Thriller,0.142726,31.0,0.157692,0.262499
52,171011,0.000000,0.000000,4.446830,1956.0,0.973380,1.000000,0.019003,2016.0,Documentary,0.008287,10.0,0.693706,0.233300
33,5618,0.000000,0.000000,4.213107,33333.0,0.955221,0.947441,0.323845,2001.0,Adventure|Animation|Fantasy,0.072744,25.0,0.222485,0.232520
7,904,0.000000,0.000000,4.226701,24883.0,0.957595,0.950497,0.241749,1954.0,Mystery|Thriller,0.128453,72.0,0.000000,0.228942
29,2858,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Drama|Romance,0.661602,32.4,0.197802,0.218785
25,1704,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Drama|Romance,0.661602,34.8,0.176410,0.217140
50,159817,0.000000,0.000000,4.444369,2948.0,0.984339,0.999447,0.028641,2006.0,Documentary,0.008287,20.0,0.304762,0.215951
1,58,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1994.0,Comedy|Drama|Romance,0.597606,38.4,0.149184,0.195354
15,1222,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Drama|War,0.600829,46.8,0.101538,0.192681
27,2248,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Drama|Romance,0.597606,44.4,0.113360,0.192599
21,1299,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1984.0,Drama|War,0.600829,50.4,0.085868,0.191476
23,1394,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Comedy,0.469613,46.8,0.101538,0.152307
9,924,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1968.0,Adventure|Drama|Sci-Fi,0.449355,69.6,0.029205,0.140510
17,1250,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1957.0,Adventure|Drama|War,0.454880,82.8,0.005275,0.140369
22,1307,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Romance,0.396409,44.4,0.113360,0.130692
16,1230,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1977.0,Comedy|Romance,0.396409,58.8,0.056615,0.126327
19,1265,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1993.0,Comedy|Fantasy|Romance,0.282689,39.6,0.141176,0.097841
24,1617,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Crime|Film-Noir|Mystery|Thriller,0.110497,34.8,0.176410,0.047569
18,1252,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1974.0,Crime|Film-Noir|Mystery|Thriller,0.110497,62.4,0.046444,0.037572

# Testing

In [292]:
ratings["userId"].value_counts().head(20)

userId
175325    33332
17035      9577
55653      9178
123465     9044
171795     9016
10202      7748
198515     7594
49305      7488
22744      7372
7858       7322
14674      6407
53192      6265
133878     6074
57304      6061
129705     5812
139018     5806
43703      5784
68797      5693
103925     5655
119247     5654
Name: count, dtype: int64

In [293]:
final_recommendations.head(175325)

,movieId,collab_score,content_score,average_rating,rating_count,popularity_score,rating_score,rating_count_score,year,genres,genre_score,movie_age,recency_score,final_score
6,858,1.000000,0.000000,4.317030,66440.0,0.979755,0.970811,0.645493,1972.0,Crime|Drama,0.585635,54.0,0.040280,0.546919
10,1193,0.546209,0.000000,4.204229,44592.0,0.953726,0.945444,0.433231,1975.0,Drama,1.000000,51.0,0.049704,0.523720
31,3114,NaN,1.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,32.4,0.197802,0.520273
28,2355,NaN,0.903345,NaN,NaN,NaN,0.000000,0.000000,1998.0,Adventure|Animation|Children|Comedy,0.162983,33.6,0.186737,0.481442
49,157296,NaN,0.785717,NaN,NaN,NaN,0.000000,0.000000,2016.0,Adventure|Animation|Comedy,0.210866,12.0,0.693706,0.480882
38,50872,NaN,0.717347,NaN,NaN,NaN,0.000000,0.000000,2007.0,Animation|Children|Drama,0.339779,22.8,0.326154,0.460719
5,750,0.865680,0.000000,4.202680,32830.0,0.952839,0.945096,0.318958,1964.0,Comedy|War,0.335635,62.0,0.019536,0.447368
46,103141,NaN,0.740759,NaN,NaN,NaN,0.000000,0.000000,2013.0,Adventure|Animation|Comedy,0.210866,15.6,0.518681,0.446669
41,78499,NaN,0.797447,NaN,NaN,NaN,0.000000,0.000000,2010.0,Adventure|Animation|Children|Comedy|Fantasy|IMAX,0.117864,19.2,0.405430,0.435505
34,6377,NaN,0.780009,NaN,NaN,NaN,0.000000,0.000000,2003.0,Adventure|Animation|Children|Comedy,0.162983,27.6,0.251282,0.429482
35,8961,NaN,0.767647,NaN,NaN,NaN,0.000000,0.000000,2004.0,Action|Adventure|Animation|Children|Comedy,0.173481,26.4,0.267559,0.428259
32,4886,NaN,0.785026,NaN,NaN,NaN,0.000000,0.000000,2001.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,30.0,0.222485,0.422953
39,68954,NaN,0.654754,NaN,NaN,NaN,0.000000,0.000000,2009.0,Adventure|Animation|Children|Drama,0.295580,20.4,0.376068,0.422070
54,201588,NaN,0.632819,NaN,NaN,NaN,0.000000,0.000000,2019.0,Adventure|Animation|Children|Comedy,0.162983,8.4,1.000000,0.419142
37,45517,NaN,0.737091,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.413788
26,2019,0.544298,0.000000,4.249622,16531.0,0.961357,0.955652,0.160606,1954.0,Action|Adventure|Drama,0.459484,72.0,0.000000,0.400773
55,202439,0.000000,0.000000,4.312254,11670.0,0.973580,0.969737,0.113379,2019.0,Comedy|Drama,0.734807,7.0,1.000000,0.397154
40,72356,NaN,0.706746,NaN,NaN,NaN,0.000000,0.000000,2009.0,Animation|Children|Comedy|Fantasy,0.136050,20.4,0.376068,0.396980
45,95858,NaN,0.699901,NaN,NaN,NaN,0.000000,0.000000,2000.0,Animation|Children|Comedy,0.162983,31.2,0.209687,0.389310
42,87876,NaN,0.650932,NaN,NaN,NaN,0.000000,0.000000,2011.0,Adventure|Animation|Children|Comedy|IMAX,0.130387,18.0,0.438462,0.374277
3,318,0.000000,0.000000,4.404614,102929.0,1.000000,0.990506,1.000000,1994.0,Crime|Drama,0.585635,32.0,0.149184,0.374112
47,109420,NaN,0.649240,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.373241
53,175831,NaN,0.670658,NaN,NaN,NaN,0.000000,0.000000,2017.0,Animation,0.000000,10.8,0.775385,0.369179
44,95856,NaN,0.770193,NaN,NaN,NaN,0.000000,0.000000,1989.0,Animation|Children,0.009669,44.4,0.113360,0.367169
2,296,0.000000,0.000000,4.196969,98409.0,0.952905,0.943811,0.956086,1994.0,Comedy|Crime|Drama|Thriller,0.448895,32.0,0.149184,0.335169
48,126405,NaN,0.679593,NaN,NaN,NaN,0.000000,0.000000,1984.0,Animation,0.000000,50.4,0.085868,0.320263
30,2959,0.000000,0.000000,4.228780,77332.0,0.959924,0.950965,0.751314,1999.0,Action|Crime|Drama|Thriller,0.385359,27.0,0.197802,0.316064
43,95375,NaN,0.633491,NaN,NaN,NaN,0.000000,0.000000,2003.0,Animation|Children,0.009669,27.6,0.251282,0.314685
20,1293,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1982.0,Drama,1.000000,52.8,0.076581,0.313583
36,44555,0.000000,0.000000,4.198770,12273.0,0.948606,0.944216,0.119238,2006.0,Drama|Romance|Thriller,0.492634,20.0,0.304762,0.309228
12,1207,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1962.0,Drama,1.000000,76.8,0.015148,0.308858
51,170705,0.000000,0.000000,4.426539,2811.0,0.979478,0.995437,0.027310,2001.0,Action|Drama|War,0.472376,25.0,0.222485,0.303658
0,50,0.000000,0.000000,4.265070,67750.0,0.968014,0.959126,0.658221,1995.0,Crime|Mystery|Thriller,0.142726,31.0,0.157692,0.262499
52,171011,0.000000,0.000000,4.446830,1956.0,0.973380,1.000000,0.019003,2016.0,Documentary,0.008287,10.0,0.693706,0.233300
33,5618,0.000000,0.000000,4.213107,33333.0,0.955221,0.947441,0.323845,2001.0,Adventure|Animation|Fantasy,0.072744,25.0,0.222485,0.232520
7,904,0.000000,0.000000,4.226701,24883.0,0.957595,0.950497,0.241749,1954.0,Mystery|Thriller,0.128453,72.0,0.000000,0.228942
29,2858,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Drama|Romance,0.661602,32.4,0.197802,0.218785
25,1704,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Drama|Romance,0.661602,34.8,0.176410,0.217140
50,159817,0.000000,0.000000,4.444369,2948.0,0.984339,0.999447,0.028641,2006.0,Documentary,0.008287,20.0,0.304762,0.215951
1,58,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1994.0,Comedy|Drama|Romance,0.597606,38.4,0.149184,0.195354
15,1222,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Drama|War,0.600829,46.8,0.101538,0.192681
27,2248,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Drama|Romance,0.597606,44.4,0.113360,0.192599
21,1299,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1984.0,Drama|War,0.600829,50.4,0.085868,0.191476
23,1394,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Comedy,0.469613,46.8,0.101538,0.152307
9,924,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1968.0,Adventure|Drama|Sci-Fi,0.449355,69.6,0.029205,0.140510
17,1250,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1957.0,Adventure|Drama|War,0.454880,82.8,0.005275,0.140369
22,1307,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Romance,0.396409,44.4,0.113360,0.130692
16,1230,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1977.0,Comedy|Romance,0.396409,58.8,0.056615,0.126327
19,1265,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1993.0,Comedy|Fantasy|Romance,0.282689,39.6,0.141176,0.097841
24,1617,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Crime|Film-Noir|Mystery|Thriller,0.110497,34.8,0.176410,0.047569
18,1252,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1974.0,Crime|Film-Noir|Mystery|Thriller,0.110497,62.4,0.046444,0.037572

In [294]:
watched_movies = ratings.loc[
    ratings["userId"] ==175325,
    "movieId"
]

print(watched_movies.tolist())

[1, 2, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 55, 57, 58, 59, 60, 62, 63, 65, 68, 69, 70, 71, 72, 73, 76, 77, 78, 79, 80, 81, 82, 85, 86, 89, 90, 92, 94, 95, 96, 97, 99, 100, 101, 104, 105, 106, 110, 111, 112, 114, 115, 116, 117, 119, 121, 122, 123, 124, 125, 127, 128, 130, 132, 133, 134, 136, 138, 141, 143, 144, 145, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164, 165, 166, 167, 168, 170, 171, 172, 173, 175, 176, 177, 178, 180, 181, 183, 184, 185, 187, 188, 190, 193, 194, 195, 196, 198, 199, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 213, 214, 215, 216, 218, 219, 220, 223, 224, 225, 227, 229, 230, 231, 232, 233, 234, 235, 236, 237, 239, 242, 245, 246, 247, 249, 252, 253, 254, 256, 259, 260, 261, 262, 263, 264, 265, 266, 268, 269, 271, 272, 273, 279, 280, 281, 282, 283, 286, 288, 289, 290, 292, 293, 294, 296, 297, 298, 299, 300, 301, 302, 303, 305, 306, 307, 308, 309, 314, 315, 316, 317, 318, 319, 320, 321, 322, 324, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 337, 339, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 352, 353, 355, 356, 357, 358, 359, 361, 363, 364, 365, 366, 367, 368, 369, 370, 372, 373, 374, 376, 377, 378, 379, 380, 381, 382, 383, 386, 389, 390, 391, 392, 393, 394, 396, 400, 403, 406, 407, 410, 412, 413, 417, 418, 420, 422, 423, 425, 426, 427, 428, 429, 431, 434, 435, 439, 440, 441, 442, 444, 446, 448, 449, 454, 455, 456, 457, 458, 459, 461, 464, 465, 466, 468, 469, 471, 472, 474, 475, 477, 479, 480, 481, 482, 483, 485, 488, 491, 492, 493, 494, 495, 496, 497, 500, 501, 503, 504, 506, 507, 508, 509, 510, 514, 515, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 541, 544, 546, 547, 548, 549, 550, 551, 552, 553, 555, 556, 559, 562, 563, 564, 565, 566, 567, 568, 570, 573, 574, 575, 576, 579, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 592, 593, 594, 595, 596, 597, 598, 599, 600, 602, 608, 609, 610, 612, 613, 615, 616, 617, 618, 620, 621, 625, 627, 628, 629, 632, 633, 635, 636, 638, 639, 645, 648, 649, 652, 653, 655, 659, 661, 663, 664, 665, 666, 668, 670, 671, 673, 674, 678, 679, 680, 681, 682, 684, 685, 690, 691, 692, 693, 696, 697, 698, 701, 702, 704, 707, 708, 709, 713, 714, 715, 716, 717, 718, 719, 722, 723, 724, 728, 729, 733, 735, 736, 737, 738, 741, 743, 745, 746, 748, 750, 751, 752, 753, 754, 756, 757, 758, 759, 760, 761, 762, 764, 765, 766, 768, 771, 772, 773, 774, 775, 778, 780, 781, 783, 784, 785, 786, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 802, 803, 805, 806, 807, 812, 820, 822, 823, 824, 825, 827, 830, 831, 832, 835, 837, 838, 841, 842, 845, 846, 848, 849, 850, 851, 852, 854, 855, 857, 858, 860, 861, 864, 865, 866, 868, 869, 872, 873, 874, 877, 878, 879, 882, 885, 886, 887, 889, 890, 892, 894, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 979, 980, 982, 983, 985, 986, 987, 988, 989, 990, 991, 994, 996, 997, 998, 999, 1000, 1003, 1006, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1019, 1020, 1022, 1023, 1024, 1025, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1044, 1046, 1047, 1049, 1050, 1051, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1065, 1066, 1067, 1068, 1069, 1070, 1073, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1099, 1100, 1101, 1102, 1103, 1104, 1109, 1111, 1112, 1114, 1116, 1117, 1120, 1121, 1123, 1124, 1125, 1127, 1128, 1129, 1130, 1131, 1132, 1134, 1135, 1136, 1137, 1140, 1143, 1144, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1156, 1157, 1160, 1161, 1162, 1163, 1164, 1165, 1169, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1309, 1310, 1312, 1313, 1315, 1320, 1321, 1323, 1326, 1327, 1329, 1330, 1331, 1333, 1334, 1335, 1337, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1360, 1361, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1382, 1385, 1386, 1387, 1388, 1391, 1392, 1393, 1394, 1396, 1397, 1398, 1399, 1401, 1404, 1405, 1406, 1407, 1408, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1419, 1422, 1424, 1425, 1428, 1429, 1430, 1437, 1438, 1441, 1443, 1444, 1446, 1447, 1449, 1450, 1454, 1458, 1464, 1465, 1466, 1467, 1471, 1472, 1473, 1475, 1476, 1477, 1479, 1480, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1490, 1493, 1496, 1497, 1498, 1499, 1500, 1502, 1504, 1508, 1509, 1511, 1513, 1514, 1516, 1517, 1518, 1522, 1523, 1527, 1529, 1531, 1533, 1534, 1535, 1537, 1539, 1542, 1544, 1545, 1546, 1552, 1553, 1554, 1555, 1557, 1562, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1575, 1577, 1579, 1580, 1584, 1585, 1587, 1589, 1590, 1593, 1594, 1596, 1597, 1598, 1600, 1603, 1605, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1619, 1620, 1622, 1623, 1624, 1625, 1627, 1631, 1632, 1633, 1635, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1656, 1658, 1659, 1660, 1661, 1663, 1664, 1665, 1666, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1676, 1677, 1678, 1680, 1682, 1683, 1684, 1686, 1687, 1688, 1689, 1690, 1693, 1694, 1695, 1696, 1697, 1699, 1701, 1703, 1704, 1711, 1714, 1715, 1716, 1717, 1719, 1721, 1722, 1724, 1726, 1727, 1728, 1729, 1730, 1732, 1733, 1734, 1735, 1747, 1748, 1752, 1753, 1754, 1757, 1759, 1760, 1762, 1768, 1770, 1771, 1772, 1773, 1777, 1779, 1780, 1781, 1783, 1784, 1785, 1791, 1792, 1793, 1794, 1795, 1797, 1798, 1799, 1801, 1804, 1805, 1806, 1809, 1810, 1811, 1815, 1816, 1821, 1827, 1829, 1833, 1834, 1835, 1836, 1839, 1840, 1841, 1844, 1845, 1846, 1847, 1848, 1851, 1856, 1857, 1859, 1860, 1861, 1862, 1865, 1871, 1872, 1875, 1876, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1888, 1889, 1890, 1891, 1892, 1893, 1895, 1896, 1897, 1900, 1901, 1903, 1904, 1906, 1907, 1908, 1909, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1920, 1921, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1982, 1983, 1984, 1985, 1986, 1987, 1991, 1992, 1994, 1995, 1996, 1997, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2028, 2029, 2030, 2031, 2033, 2034, 2038, 2042, 2045, 2046, 2048, 2052, 2053, 2054, 2057, 2058, 2059, 2060, 2061, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2078, 2080, 2081, 2082, 2083, 2085, 2087, 2089, 2090, 2093, 2094, 2096, 2097, 2099, 2100, 2102, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2143, 2144, 2145, 2146, 2148, 2149, 2150, 2151, 2154, 2155, 2156, 2157, 2159, 2160, 2161, 2163, 2164, 2165, 2167, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2191, 2192, 2193, 2194, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2217, 2219, 2220, 2221, 2222, 2224, 2225, 2226, 2227, 2229, 2231, 2232, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2243, 2245, 2247, 2248, 2251, 2253, 2255, 2257, 2259, 2261, 2262, 2265, 2268, 2269, 2271, 2272, 2273, 2275, 2276, 2278, 2279, 2280, 2282, 2283, 2284, 2285, 2287, 2288, 2289, 2290, 2291, 2294, 2295, 2296, 2297, 2300, 2301, 2302, 2303, 2304, 2305, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2335, 2336, 2337, 2340, 2341, 2342, 2344, 2345, 2346, 2347, 2348, 2349, 2351, 2352, 2353, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2366, 2367, 2369, 2370, 2371, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2384, 2385, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2409, 2410, 2411, 2412, 2413, 2414, 2416, 2419, 2420, 2421, 2423, 2424, 2425, 2426, 2427, 2428, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2439, 2440, 2441, 2442, 2443, 2444, 2446, 2447, 2450, 2451, 2454, 2455, 2456, 2457, 2459, 2460, 2461, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2474, 2475, 2476, 2478, 2480, 2481, 2483, 2485, 2487, 2488, 2490, 2493, 2494, 2495, 2496, 2497, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2509, 2511, 2512, 2513, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2537, 2538, 2539, 2541, 2542, 2544, 2545, 2548, 2550, 2551, 2552, 2553, 2557, 2558, 2560, 2561, 2562, 2564, 2565, 2567, 2570, 2571, 2572, 2573, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2585, 2589, 2590, 2591, 2593, 2594, 2595, 2596, 2598, 2599, 2600, 2602, 2603, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2616, 2617, 2618, 2620, 2621, 2624, 2625, 2626, 2628, 2630, 2632, 2633, 2634, 2639, 2640, 2641, 2642, 2643, 2644, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2677, 2678, 2679, 2682, 2683, 2685, 2686, 2687, 2689, 2690, 2691, 2692, 2694, 2695, 2696, 2697, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2710, 2712, 2713, 2715, 2716, 2717, 2718, 2719, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2738, 2739, 2742, 2743, 2744, 2745, 2746, 2747, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2769, 2770, 2771, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2801, 2802, 2803, 2804, 2805, 2806, 2808, 2810, 2813, 2814, 2815, 2819, 2820, 2821, 2823, 2824, 2825, 2826, 2827, 2829, 2830, 2833, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2846, 2847, 2848, 2849, 2850, 2852, 2853, 2854, 2855, 2857, 2858, 2859, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2888, 2890, 2891, 2892, 2894, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2907, 2908, 2910, 2911, 2912, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2957, 2959, 2960, 2962, 2963, 2964, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2975, 2976, 2977, 2978, 2979, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2993, 2994, 2995, 2996, 2997, 3000, 3002, 3003, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3044, 3045, 3046, 3051, 3052, 3053, 3055, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3139, 3140, 3141, 3143, 3145, 3146, 3147, 3148, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3167, 3168, 3169, 3171, 3173, 3174, 3175, 3176, 3178, 3179, 3181, 3182, 3183, 3185, 3186, 3187, 3188, 3190, 3191, 3192, 3194, 3195, 3196, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3215, 3216, 3217, 3218, 3220, 3221, 3222, 3223, 3224, 3225, 3227, 3229, 3230, 3231, 3232, 3235, 3236, 3238, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3269, 3271, 3272, 3273, 3275, 3277, 3278, 3280, 3281, 3282, 3283, 3284, 3285, 3289, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3316, 3317, 3318, 3319, 3320, 3325, 3327, 3328, 3329, 3330, 3331, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3346, 3347, 3348, 3350, 3351, 3354, 3355, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3368, 3369, 3371, 3372, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3386, 3388, 3392, 3396, 3397, 3398, 3404, 3405, 3406, 3407, 3408, 3409, 3412, 3413, 3414, 3415, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3435, 3437, 3438, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3455, 3456, 3457, 3459, 3461, 3462, 3465, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3483, 3484, 3485, 3487, 3489, 3490, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3514, 3515, 3518, 3521, 3522, 3524, 3525, 3526, 3527, 3528, 3529, 3530, 3531, 3533, 3534, 3535, 3536, 3538, 3539, 3541, 3542, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3562, 3565, 3566, 3568, 3569, 3570, 3571, 3572, 3575, 3576, 3577, 3578, 3579, 3581, 3583, 3584, 3585, 3586, 3587, 3588, 3591, 3592, 3594, 3598, 3599, 3600, 3602, 3603, 3604, 3605, 3606, 3608, 3609, 3611, 3612, 3613, 3614, 3615, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3626, 3627, 3629, 3630, 3631, 3632, 3633, 3634, 3635, 3636, 3637, 3638, 3639, 3640, 3641, 3642, 3643, 3645, 3646, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3668, 3670, 3671, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3691, 3692, 3693, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713, 3714, 3717, 3720, 3721, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3745, 3746, 3747, 3749, 3751, 3752, 3753, 3755, 3756, 3757, 3759, 3760, 3761, 3763, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3775, 3776, 3777, 3778, 3779, 3780, 3783, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3794, 3795, 3796, 3798, 3800, 3801, 3802, 3803, 3804, 3805, 3807, 3808, 3811, 3812, 3813, 3814, 3816, 3817, 3819, 3821, 3822, 3823, 3825, 3826, 3827, 3830, 3831, 3832, 3833, 3835, 3836, 3837, 3838, 3839, 3840, 3841, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3850, 3851, 3852, 3853, 3854, 3855, 3857, 3858, 3859, 3860, 3861, 3862, 3863, 3867, 3868, 3869, 3870, 3871, 3872, 3873, 3874, 3875, 3876, 3878, 3880, 3882, 3883, 3885, 3892, 3893, 3894, 3895, 3896, 3897, 3898, 3900, 3901, 3902, 3903, 3909, 3910, 3911, 3912, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3927, 3928, 3929, 3930, 3931, 3932, 3933, 3934, 3936, 3937, 3938, 3939, 3941, 3942, 3943, 3947, 3948, 3949, 3950, 3951, 3952, 3953, 3954, 3955, 3957, 3959, 3960, 3963, 3964, 3965, 3966, 3967, 3968, 3969, 3970, 3972, 3976, 3977, 3979, 3980, 3981, 3983, 3984, 3985, 3986, 3988, 3989, 3992, 3993, 3994, 3995, 3996, 3998, 3999, 4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009, 4010, 4011, 4014, 4015, 4016, 4017, 4018, 4019, 4020, 4021, 4022, 4023, 4024, 4025, 4026, 4027, 4028, 4029, 4030, 4031, 4032, 4033, 4034, 4035, 4036, 4037, 4038, 4039, 4041, 4042, 4043, 4044, 4045, 4046, 4047, 4052, 4053, 4054, 4055, 4056, 4058, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4069, 4072, 4074, 4077, 4079, 4080, 4082, 4083, 4084, 4085, 4086, 4088, 4090, 4092, 4095, 4097, 4098, 4101, 4103, 4105, 4106, 4107, 4108, 4110, 4111, 4112, 4113, 4114, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4125, 4126, 4128, 4129, 4132, 4133, 4135, 4136, 4144, 4145, 4146, 4147, 4148, 4150, 4151, 4152, 4155, 4156, 4157, 4159, 4160, 4161, 4164, 4165, 4166, 4168, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4178, 4179, 4180, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4194, 4195, 4197, 4198, 4199, 4200, 4201, 4204, 4205, 4206, 4207, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4216, 4217, 4218, 4219, 4220, 4222, 4225, 4226, 4227, 4228, 4232, 4233, 4234, 4235, 4236, 4237, 4239, 4240, 4243, 4244, 4245, 4246, 4251, 4252, 4253, 4254, 4255, 4256, 4258, 4259, 4260, 4261, 4262, 4263, 4266, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4280, 4281, 4282, 4283, 4285, 4286, 4288, 4289, 4290, 4291, 4292, 4294, 4296, 4297, 4298, 4299, 4300, 4301, 4302, 4303, 4304, 4305, 4306, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4329, 4330, 4333, 4334, 4336, 4337, 4338, 4339, 4340, 4342, 4344, 4345, 4347, 4349, 4350, 4351, 4352, 4356, 4357, 4359, 4360, 4361, 4362, 4363, 4366, 4367, 4369, 4370, 4372, 4373, 4375, 4378, 4380, 4381, 4383, 4384, 4385, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4399, 4401, 4403, 4404, 4405, 4406, 4407, 4408, 4409, 4410, 4411, 4412, 4414, 4415, 4416, 4417, 4419, 4420, 4421, 4422, 4423, 4424, 4426, 4427, 4428, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4438, 4439, 4440, 4441, 4442, 4443, 4444, 4446, 4447, 4448, 4449, 4450, 4451, 4454, 4459, 4463, 4464, 4465, 4466, 4467, 4468, 4470, 4474, 4475, 4478, 4479, 4480, 4481, 4484, 4487, 4488, 4489, 4492, 4495, 4496, 4497, 4498, 4499, 4500, 4501, 4503, 4506, 4508, 4509, 4510, 4515, 4517, 4518, 4519, 4520, 4522, 4523, 4524, 4528, 4529, 4530, 4531, 4532, 4533, 4535, 4537, 4538, 4541, 4542, 4543, 4545, 4546, 4547, 4552, 4553, 4555, 4556, 4557, 4558, 4559, 4561, 4563, 4564, 4565, 4566, 4569, 4570, 4571, 4572, 4573, 4574, 4575, 4577, 4578, 4580, 4581, 4584, 4586, 4587, 4590, 4595, 4599, 4602, 4603, 4604, 4605, 4607, 4608, 4609, 4611, 4612, 4613, 4614, 4615, 4616, 4618, 4619, 4621, 4623, 4624, 4626, 4628, 4631, 4632, 4633, 4636, 4637, 4638, 4639, 4640, 4641, 4642, 4643, 4644, 4645, 4646, 4647, 4648, 4649, 4651, 4652, 4654, 4656, 4658, 4659, 4660, 4661, 4664, 4665, 4666, 4668, 4670, 4671, 4672, 4673, 4677, 4678, 4679, 4680, 4681, 4682, 4683, 4687, 4688, 4689, 4690, 4692, 4693, 4694, 4695, 4696, 4697, 4698, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4708, 4709, 4710, 4711, 4712, 4713, 4

In [295]:
set(final_recommendations["movieId"]).intersection(set(watched_movies))

{50,
 58,
 296,
 318,
 750,
 858,
 904,
 924,
 1193,
 1207,
 1222,
 1230,
 1250,
 1252,
 1265,
 1293,
 1299,
 1307,
 1394,
 1617,
 1704,
 2019,
 2248,
 2355,
 2858,
 2959,
 3114,
 4886,
 5618,
 6377,
 8961,
 44555,
 45517,
 50872,
 68954,
 72356,
 78499,
 87876,
 95375,
 95856,
 95858,
 103141,
 109420,
 126405,
 157296,
 159817,
 170705,
 171011,
 175831,
 201588,
 202439}

In [296]:
final_recommendations["movieId"].duplicated().sum()

np.int64(0)

In [297]:
final_recommendations.isna().sum()

movieId                0
collab_score          36
content_score          0
average_rating        36
rating_count          36
popularity_score      36
rating_score           0
rating_count_score     0
year                   0
genres                 0
genre_score            0
movie_age              0
recency_score          0
final_score            0
dtype: int64

In [298]:
final_recommendations.head(99999999)

,movieId,collab_score,content_score,average_rating,rating_count,popularity_score,rating_score,rating_count_score,year,genres,genre_score,movie_age,recency_score,final_score
6,858,1.000000,0.000000,4.317030,66440.0,0.979755,0.970811,0.645493,1972.0,Crime|Drama,0.585635,54.0,0.040280,0.546919
10,1193,0.546209,0.000000,4.204229,44592.0,0.953726,0.945444,0.433231,1975.0,Drama,1.000000,51.0,0.049704,0.523720
31,3114,NaN,1.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,32.4,0.197802,0.520273
28,2355,NaN,0.903345,NaN,NaN,NaN,0.000000,0.000000,1998.0,Adventure|Animation|Children|Comedy,0.162983,33.6,0.186737,0.481442
49,157296,NaN,0.785717,NaN,NaN,NaN,0.000000,0.000000,2016.0,Adventure|Animation|Comedy,0.210866,12.0,0.693706,0.480882
38,50872,NaN,0.717347,NaN,NaN,NaN,0.000000,0.000000,2007.0,Animation|Children|Drama,0.339779,22.8,0.326154,0.460719
5,750,0.865680,0.000000,4.202680,32830.0,0.952839,0.945096,0.318958,1964.0,Comedy|War,0.335635,62.0,0.019536,0.447368
46,103141,NaN,0.740759,NaN,NaN,NaN,0.000000,0.000000,2013.0,Adventure|Animation|Comedy,0.210866,15.6,0.518681,0.446669
41,78499,NaN,0.797447,NaN,NaN,NaN,0.000000,0.000000,2010.0,Adventure|Animation|Children|Comedy|Fantasy|IMAX,0.117864,19.2,0.405430,0.435505
34,6377,NaN,0.780009,NaN,NaN,NaN,0.000000,0.000000,2003.0,Adventure|Animation|Children|Comedy,0.162983,27.6,0.251282,0.429482
35,8961,NaN,0.767647,NaN,NaN,NaN,0.000000,0.000000,2004.0,Action|Adventure|Animation|Children|Comedy,0.173481,26.4,0.267559,0.428259
32,4886,NaN,0.785026,NaN,NaN,NaN,0.000000,0.000000,2001.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,30.0,0.222485,0.422953
39,68954,NaN,0.654754,NaN,NaN,NaN,0.000000,0.000000,2009.0,Adventure|Animation|Children|Drama,0.295580,20.4,0.376068,0.422070
54,201588,NaN,0.632819,NaN,NaN,NaN,0.000000,0.000000,2019.0,Adventure|Animation|Children|Comedy,0.162983,8.4,1.000000,0.419142
37,45517,NaN,0.737091,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.413788
26,2019,0.544298,0.000000,4.249622,16531.0,0.961357,0.955652,0.160606,1954.0,Action|Adventure|Drama,0.459484,72.0,0.000000,0.400773
55,202439,0.000000,0.000000,4.312254,11670.0,0.973580,0.969737,0.113379,2019.0,Comedy|Drama,0.734807,7.0,1.000000,0.397154
40,72356,NaN,0.706746,NaN,NaN,NaN,0.000000,0.000000,2009.0,Animation|Children|Comedy|Fantasy,0.136050,20.4,0.376068,0.396980
45,95858,NaN,0.699901,NaN,NaN,NaN,0.000000,0.000000,2000.0,Animation|Children|Comedy,0.162983,31.2,0.209687,0.389310
42,87876,NaN,0.650932,NaN,NaN,NaN,0.000000,0.000000,2011.0,Adventure|Animation|Children|Comedy|IMAX,0.130387,18.0,0.438462,0.374277
3,318,0.000000,0.000000,4.404614,102929.0,1.000000,0.990506,1.000000,1994.0,Crime|Drama,0.585635,32.0,0.149184,0.374112
47,109420,NaN,0.649240,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.373241
53,175831,NaN,0.670658,NaN,NaN,NaN,0.000000,0.000000,2017.0,Animation,0.000000,10.8,0.775385,0.369179
44,95856,NaN,0.770193,NaN,NaN,NaN,0.000000,0.000000,1989.0,Animation|Children,0.009669,44.4,0.113360,0.367169
2,296,0.000000,0.000000,4.196969,98409.0,0.952905,0.943811,0.956086,1994.0,Comedy|Crime|Drama|Thriller,0.448895,32.0,0.149184,0.335169
48,126405,NaN,0.679593,NaN,NaN,NaN,0.000000,0.000000,1984.0,Animation,0.000000,50.4,0.085868,0.320263
30,2959,0.000000,0.000000,4.228780,77332.0,0.959924,0.950965,0.751314,1999.0,Action|Crime|Drama|Thriller,0.385359,27.0,0.197802,0.316064
43,95375,NaN,0.633491,NaN,NaN,NaN,0.000000,0.000000,2003.0,Animation|Children,0.009669,27.6,0.251282,0.314685
20,1293,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1982.0,Drama,1.000000,52.8,0.076581,0.313583
36,44555,0.000000,0.000000,4.198770,12273.0,0.948606,0.944216,0.119238,2006.0,Drama|Romance|Thriller,0.492634,20.0,0.304762,0.309228
12,1207,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1962.0,Drama,1.000000,76.8,0.015148,0.308858
51,170705,0.000000,0.000000,4.426539,2811.0,0.979478,0.995437,0.027310,2001.0,Action|Drama|War,0.472376,25.0,0.222485,0.303658
0,50,0.000000,0.000000,4.265070,67750.0,0.968014,0.959126,0.658221,1995.0,Crime|Mystery|Thriller,0.142726,31.0,0.157692,0.262499
52,171011,0.000000,0.000000,4.446830,1956.0,0.973380,1.000000,0.019003,2016.0,Documentary,0.008287,10.0,0.693706,0.233300
33,5618,0.000000,0.000000,4.213107,33333.0,0.955221,0.947441,0.323845,2001.0,Adventure|Animation|Fantasy,0.072744,25.0,0.222485,0.232520
7,904,0.000000,0.000000,4.226701,24883.0,0.957595,0.950497,0.241749,1954.0,Mystery|Thriller,0.128453,72.0,0.000000,0.228942
29,2858,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Drama|Romance,0.661602,32.4,0.197802,0.218785
25,1704,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Drama|Romance,0.661602,34.8,0.176410,0.217140
50,159817,0.000000,0.000000,4.444369,2948.0,0.984339,0.999447,0.028641,2006.0,Documentary,0.008287,20.0,0.304762,0.215951
1,58,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1994.0,Comedy|Drama|Romance,0.597606,38.4,0.149184,0.195354
15,1222,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Drama|War,0.600829,46.8,0.101538,0.192681
27,2248,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Drama|Romance,0.597606,44.4,0.113360,0.192599
21,1299,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1984.0,Drama|War,0.600829,50.4,0.085868,0.191476
23,1394,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Comedy,0.469613,46.8,0.101538,0.152307
9,924,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1968.0,Adventure|Drama|Sci-Fi,0.449355,69.6,0.029205,0.140510
17,1250,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1957.0,Adventure|Drama|War,0.454880,82.8,0.005275,0.140369
22,1307,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Romance,0.396409,44.4,0.113360,0.130692
16,1230,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1977.0,Comedy|Romance,0.396409,58.8,0.056615,0.126327
19,1265,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1993.0,Comedy|Fantasy|Romance,0.282689,39.6,0.141176,0.097841
24,1617,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Crime|Film-Noir|Mystery|Thriller,0.110497,34.8,0.176410,0.047569
18,1252,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1974.0,Crime|Film-Noir|Mystery|Thriller,0.110497,62.4,0.046444,0.037572

In [299]:
ratings["userId"].value_counts().sort_values().head(20)

userId
183776    20
192976    20
11855     20
103561    20
119491    20
103572    20
4618      20
169930    20
192998    20
169897    20
71245     20
18281     20
140640    20
107340    20
25645     20
25646     20
107312    20
13359     20
35499     20
119546    20
Name: count, dtype: int64

In [300]:
final_recommendations.head(119546)

,movieId,collab_score,content_score,average_rating,rating_count,popularity_score,rating_score,rating_count_score,year,genres,genre_score,movie_age,recency_score,final_score
6,858,1.000000,0.000000,4.317030,66440.0,0.979755,0.970811,0.645493,1972.0,Crime|Drama,0.585635,54.0,0.040280,0.546919
10,1193,0.546209,0.000000,4.204229,44592.0,0.953726,0.945444,0.433231,1975.0,Drama,1.000000,51.0,0.049704,0.523720
31,3114,NaN,1.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,32.4,0.197802,0.520273
28,2355,NaN,0.903345,NaN,NaN,NaN,0.000000,0.000000,1998.0,Adventure|Animation|Children|Comedy,0.162983,33.6,0.186737,0.481442
49,157296,NaN,0.785717,NaN,NaN,NaN,0.000000,0.000000,2016.0,Adventure|Animation|Comedy,0.210866,12.0,0.693706,0.480882
38,50872,NaN,0.717347,NaN,NaN,NaN,0.000000,0.000000,2007.0,Animation|Children|Drama,0.339779,22.8,0.326154,0.460719
5,750,0.865680,0.000000,4.202680,32830.0,0.952839,0.945096,0.318958,1964.0,Comedy|War,0.335635,62.0,0.019536,0.447368
46,103141,NaN,0.740759,NaN,NaN,NaN,0.000000,0.000000,2013.0,Adventure|Animation|Comedy,0.210866,15.6,0.518681,0.446669
41,78499,NaN,0.797447,NaN,NaN,NaN,0.000000,0.000000,2010.0,Adventure|Animation|Children|Comedy|Fantasy|IMAX,0.117864,19.2,0.405430,0.435505
34,6377,NaN,0.780009,NaN,NaN,NaN,0.000000,0.000000,2003.0,Adventure|Animation|Children|Comedy,0.162983,27.6,0.251282,0.429482
35,8961,NaN,0.767647,NaN,NaN,NaN,0.000000,0.000000,2004.0,Action|Adventure|Animation|Children|Comedy,0.173481,26.4,0.267559,0.428259
32,4886,NaN,0.785026,NaN,NaN,NaN,0.000000,0.000000,2001.0,Adventure|Animation|Children|Comedy|Fantasy,0.141436,30.0,0.222485,0.422953
39,68954,NaN,0.654754,NaN,NaN,NaN,0.000000,0.000000,2009.0,Adventure|Animation|Children|Drama,0.295580,20.4,0.376068,0.422070
54,201588,NaN,0.632819,NaN,NaN,NaN,0.000000,0.000000,2019.0,Adventure|Animation|Children|Comedy,0.162983,8.4,1.000000,0.419142
37,45517,NaN,0.737091,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.413788
26,2019,0.544298,0.000000,4.249622,16531.0,0.961357,0.955652,0.160606,1954.0,Action|Adventure|Drama,0.459484,72.0,0.000000,0.400773
55,202439,0.000000,0.000000,4.312254,11670.0,0.973580,0.969737,0.113379,2019.0,Comedy|Drama,0.734807,7.0,1.000000,0.397154
40,72356,NaN,0.706746,NaN,NaN,NaN,0.000000,0.000000,2009.0,Animation|Children|Comedy|Fantasy,0.136050,20.4,0.376068,0.396980
45,95858,NaN,0.699901,NaN,NaN,NaN,0.000000,0.000000,2000.0,Animation|Children|Comedy,0.162983,31.2,0.209687,0.389310
42,87876,NaN,0.650932,NaN,NaN,NaN,0.000000,0.000000,2011.0,Adventure|Animation|Children|Comedy|IMAX,0.130387,18.0,0.438462,0.374277
3,318,0.000000,0.000000,4.404614,102929.0,1.000000,0.990506,1.000000,1994.0,Crime|Drama,0.585635,32.0,0.149184,0.374112
47,109420,NaN,0.649240,NaN,NaN,NaN,0.000000,0.000000,2006.0,Animation|Children|Comedy,0.162983,24.0,0.304762,0.373241
53,175831,NaN,0.670658,NaN,NaN,NaN,0.000000,0.000000,2017.0,Animation,0.000000,10.8,0.775385,0.369179
44,95856,NaN,0.770193,NaN,NaN,NaN,0.000000,0.000000,1989.0,Animation|Children,0.009669,44.4,0.113360,0.367169
2,296,0.000000,0.000000,4.196969,98409.0,0.952905,0.943811,0.956086,1994.0,Comedy|Crime|Drama|Thriller,0.448895,32.0,0.149184,0.335169
48,126405,NaN,0.679593,NaN,NaN,NaN,0.000000,0.000000,1984.0,Animation,0.000000,50.4,0.085868,0.320263
30,2959,0.000000,0.000000,4.228780,77332.0,0.959924,0.950965,0.751314,1999.0,Action|Crime|Drama|Thriller,0.385359,27.0,0.197802,0.316064
43,95375,NaN,0.633491,NaN,NaN,NaN,0.000000,0.000000,2003.0,Animation|Children,0.009669,27.6,0.251282,0.314685
20,1293,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1982.0,Drama,1.000000,52.8,0.076581,0.313583
36,44555,0.000000,0.000000,4.198770,12273.0,0.948606,0.944216,0.119238,2006.0,Drama|Romance|Thriller,0.492634,20.0,0.304762,0.309228
12,1207,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1962.0,Drama,1.000000,76.8,0.015148,0.308858
51,170705,0.000000,0.000000,4.426539,2811.0,0.979478,0.995437,0.027310,2001.0,Action|Drama|War,0.472376,25.0,0.222485,0.303658
0,50,0.000000,0.000000,4.265070,67750.0,0.968014,0.959126,0.658221,1995.0,Crime|Mystery|Thriller,0.142726,31.0,0.157692,0.262499
52,171011,0.000000,0.000000,4.446830,1956.0,0.973380,1.000000,0.019003,2016.0,Documentary,0.008287,10.0,0.693706,0.233300
33,5618,0.000000,0.000000,4.213107,33333.0,0.955221,0.947441,0.323845,2001.0,Adventure|Animation|Fantasy,0.072744,25.0,0.222485,0.232520
7,904,0.000000,0.000000,4.226701,24883.0,0.957595,0.950497,0.241749,1954.0,Mystery|Thriller,0.128453,72.0,0.000000,0.228942
29,2858,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1999.0,Drama|Romance,0.661602,32.4,0.197802,0.218785
25,1704,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Drama|Romance,0.661602,34.8,0.176410,0.217140
50,159817,0.000000,0.000000,4.444369,2948.0,0.984339,0.999447,0.028641,2006.0,Documentary,0.008287,20.0,0.304762,0.215951
1,58,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1994.0,Comedy|Drama|Romance,0.597606,38.4,0.149184,0.195354
15,1222,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Drama|War,0.600829,46.8,0.101538,0.192681
27,2248,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Drama|Romance,0.597606,44.4,0.113360,0.192599
21,1299,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1984.0,Drama|War,0.600829,50.4,0.085868,0.191476
23,1394,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1987.0,Comedy,0.469613,46.8,0.101538,0.152307
9,924,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1968.0,Adventure|Drama|Sci-Fi,0.449355,69.6,0.029205,0.140510
17,1250,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1957.0,Adventure|Drama|War,0.454880,82.8,0.005275,0.140369
22,1307,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1989.0,Comedy|Romance,0.396409,44.4,0.113360,0.130692
16,1230,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1977.0,Comedy|Romance,0.396409,58.8,0.056615,0.126327
19,1265,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1993.0,Comedy|Fantasy|Romance,0.282689,39.6,0.141176,0.097841
24,1617,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1997.0,Crime|Film-Noir|Mystery|Thriller,0.110497,34.8,0.176410,0.047569
18,1252,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1974.0,Crime|Film-Noir|Mystery|Thriller,0.110497,62.4,0.046444,0.037572